services:
  payload:
    image: cms:latest
    container_name: cms
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - csclub

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - csclub

volumes:
  data:

networks:
  csclub:
    external: true
